# Generated by Django 3.2.9 on 2021-11-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methods',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
